export const SITE_CONFIG = {
  version: '2.3.4',
  name: '中臺機器人研究社',
  shortName: '中臺機器人研究社',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://robotctust.com',
  locale: 'zh-TW',
  creator: '中臺機器人研究社',
  publisher: '中臺機器人研究社',
  keywords: [
    '中臺機器人研究社',
    '社團網站',
    '機器人研究',
    '機器人社團',
    '機器人社',
    '機器人',
    '中臺科技大學',
    '中臺科大',
    '研究社',
    '機器人技術',
    '學習平台',
    'Robot',
    'CTUST',
    'robotctust',
    'Robot CTUST',
    'Robotics Research',
    'Robotics Research Club',
    'Robotics Research Club of CTUST',
  ],
} as const
